data:
    name: wireframe_eval
    dataset_dir: Wireframe_raw
    batch_size: 1
    # resize: None
    num_workers: 2
    seed: 0
model:
    name: deeplsd
    tiny: False
    sharpen: True
    line_neighborhood: 5
    loss_weights:
        df: 1
        angle: 1.
    detect_lines: True
    multiscale: False
    scale_factors: [1., 1.5]
    line_detection_params:
        grad_nfa: True
        merge: False
        optimize: False
        use_vps: True
        optimize_vps: True
        filtering: 'strict'
        grad_thresh: 3
