data:
    name: eth3d
    dataset_dir: ETH3D
    downsize_factor: 8
    inpainted_depth: True
    batch_size: 1
    num_workers: 4
model:
    name: deeplsd
    tiny: False
    sharpen: True
    line_neighborhood: 5
    loss_weights:
        df: 1.
        angle: 1.
    detect_lines: True
    multiscale: False
    scale_factors: [1., 1.5]
    line_detection_params:
        grad_nfa: True
        merge: False
        use_vps: False
        optimize: False
        optimize_vps: False
        filtering: True
        grad_thresh: 3
